import "dotenv/config";
import path from "path";

// Required environment variables
// Please set these in your .env file
const {
  PORT,
  PINECONE_API_KEY,
  PINECONE_INDEX,
  OPENAI_API_KEY,
  OPENAI_EMBEDDING_MODEL_NAME,
  MONGODB_URI,
  CORS_ORIGINS,
  SLACK_TOKEN,
  SLACK_BOT_ID,
  NOTION_KEY,
  TELEGRAM_BOT_TOKEN,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  GITHUB_APP_ID,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
  GOOGLE_SERVICE_ACCOUNT_EMAIL,
  GOOGLE_PRIVATE_KEY,
  IMPERSONATED_USER_EMAIL,
  CLIENT_URL,
  JWT_SECRET,
  FIREFLIES_API_KEY,
  ANTHROPIC_API_KEY,
  FIREBASE_SERVICE_ACCOUNT_JSON,
  FIREBASE_STORAGE_BUCKET,
} = process.env;

const TEMP_DIR = path.join(__dirname, "../../temp");

// Export environment variables
// Note: All sensitive values should be set in .env file
export {
  PORT,
  PINECONE_API_KEY,
  PINECONE_INDEX,
  OPENAI_API_KEY,
  OPENAI_EMBEDDING_MODEL_NAME,
  MONGODB_URI,
  CORS_ORIGINS,
  SLACK_TOKEN,
  SLACK_BOT_ID,
  NOTION_KEY,
  TELEGRAM_BOT_TOKEN,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  GITHUB_APP_ID,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
  GOOGLE_SERVICE_ACCOUNT_EMAIL,
  GOOGLE_PRIVATE_KEY,
  IMPERSONATED_USER_EMAIL,
  CLIENT_URL,
  JWT_SECRET,
  TEMP_DIR,
  FIREFLIES_API_KEY,
  ANTHROPIC_API_KEY,
  FIREBASE_SERVICE_ACCOUNT_JSON,
  FIREBASE_STORAGE_BUCKET,
};
